### ISSUE TITLE
Desktop screen share failing with TypeError: e.split is not a function

### ISSUE THREAD

**Issue by Kyoshiro-san** [igniterealtime/Openfire-Meetings#62]
Hi,

I'm trying to get desktop screen sharing to work using Firefox 59 on Ubuntu/Linux 17.10 and OpenFire server 4.2.3, ofmeet 0.9.3. When I click on the screen share button, I get an red popup box saying _Screen sharing extension failed to install_ and a few JS console errors:

> [react/features/base/tracks/functions.js] <t.a/<>:  Failed to create local tracks Array [ "desktop" ] TypeError: e.split is not a function
> [conference.js] <_handleScreenSharingError>:  failed to share local desktop TypeError: e.split is not a function
> [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  TypeError: e.split is not a function

I thought there was no need for an extension anymore using Firefox > 52, am I wrong ?
What could be the problem here ?

Thank you very much,
Kind Regards.

Stack traces here:
[20180326-openfire-meetings-desktop-share.jsconsole.txt.gz](https://github.com/igniterealtime/Openfire-Meetings/files/1848247/20180326-openfire-meetings-desktop-share.jsconsole.txt.gz)

**Comment by Kyoshiro-san** [comment]
Well, this upstream issue seems related https://github.com/jitsi/jitsi-meet/issues/2350
